apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.nexusServiceName }}
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: {{ .Values.imageName}}
    name: latest