apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.nexusServiceName }}
  name: REPLACE_PVC
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}