apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: {{ .Values.nexusServiceName }}
  name: {{ .Values.nexusServiceName }}
spec:
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: {{ .Values.nexusServiceName }}
    deploymentconfig: {{ .Values.nexusServiceName }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}