apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  generation: 1
  labels:
    app: {{ .Values.nexusServiceName }}
  name: {{ .Values.nexusServiceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.nexusServiceName }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: {{ .Values.nexusServiceName }}
        deployment: {{ .Values.nexusServiceName }}
    spec:
      containers:
      - env:
        - name: INSTALL4J_ADD_VM_PARAMS
          value: -Djava.util.prefs.userRoot=/nexus-data/javaprefs
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'curl -siu admin:$(cat /nexus-data/admin.password) http://localhost:8081/service/metrics/healthcheck
              | grep healthy | grep true

              '
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: {{ .Values.nexusServiceName }}
        ports:
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'curl -siu admin:$(cat /nexus-data/admin.password) http://localhost:8081/service/metrics/ping
              | grep pong

              '
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: '1'
            memory: {{ .Values.memoryLimit }}
          requests:
            cpu: 500m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-data
        image: nexus3:latest
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-data-pvc
