# Default values for nexus-chart.
# This is a YAML-formatted file.

nexusServiceName: nexus3
hostname: nexus3-uycvax.apps.ap46.prod.nextcle.com
imageName: quay.io/jason.wong76/nexus3:latest
memoryLimit: 2703Mi
